CalendarApi/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('lessons_app.urls')),
    # path('auth/', include('djoser.urls')),
    # path('auth/', include('djoser.urls.authtoken')),
    path('auth/', include('djoser.urls.jwt')),
]

lessons_app/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    CustomRegistrationView, CustomLogOutView, CustomLoginView, AddLessonView,
    DeleteLessonView, LessonView, LessonByUserView,
    InfoView,
    SettingsAP, AddLessonAP, TimeBlockerAP, StudentsAP, StudentDetailAP,
    UsersAPI, RegistrationAPI, RelevantLessonsAPI, LessonsViewSet,
    LessonsAdminViewSet, RelevantLessonsAdminViewSet, DeleteUserAPI,
    TimeBlockAPI, TimeBlockAdminAPI, StudentAdminAPI
)

router = DefaultRouter()
router.register('api/set-my-lessons', LessonsViewSet,
                basename='my_lessons')
router.register('api/all-lessons', LessonsAdminViewSet)
router.register('api/all-relevant-lessons', RelevantLessonsAdminViewSet)
router.register('api/admin/admin-panel/timeblock', TimeBlockAdminAPI)
router.register('api/admin/admin-panel/students', StudentAdminAPI)

urlpatterns = [
    path('', LessonView.as_view(), name='home_url'),
    path('my-lessons', LessonByUserView.as_view(),
         name='lesson_by_student_url'),
    path('register', CustomRegistrationView.as_view(),
         name='registration_url'),
    path('logout', CustomLogOutView.as_view(), name='logout_url'),
    path('login', CustomLoginView.as_view(), name='login_url'),
    path('add-lesson', AddLessonView.as_view(), name='add_lesson_url'),
    path('delete-lesson/<int:pk>/', DeleteLessonView.as_view(),
         name='del_lesson_url'),
    path('info', InfoView.as_view(), name='info_url'),

    # Admin panel
    path('admin-panel/settings', SettingsAP.as_view(),
         name='settingAP_url'),
    path('admin-panel/add-lesson', AddLessonAP.as_view(),
         name='add_lesson_AP_url'),
    path('admin-panel/block-time', TimeBlockerAP.as_view(),
         name='time_blocker_AP_url'),
    path('admin-panel/students', StudentsAP.as_view(),
         name='students_AP_url'),
    path('admin-panel/students/<int:pk>', StudentDetailAP.as_view(),
         name='student_detail_AP_url'),

    # API
    path('api/registration', RegistrationAPI.as_view()),
    path('api/get-users', UsersAPI.as_view()),
    path('api/get-relevant-lessons', RelevantLessonsAPI.as_view()),
    path('api/delete-user/<int:pk>/', DeleteUserAPI.as_view()),

    # Admin panel API
    path('api/get-timeblocks', TimeBlockAPI.as_view()),
]

urlpatterns += router.urls

lessons_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import gettext as _

from CalendarApi.constraints import (
    C_salary_common, C_salary_high
)


class Lesson(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    salary = models.IntegerField()
    time = models.TimeField()
    date = models.DateField()

    class Meta:
        verbose_name = _('Lesson')
        verbose_name_plural = _('Lessons')
        ordering = ('date', 'time')

    def __str__(self):
        return _('The Lesson class: id = {}').format(self.pk)

    def get_absolute_url(self):
        return reverse('add_lesson_url', kwargs={'pk': self.pk})


class UserDetail(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                related_name='details')
    phone = models.CharField(max_length=11, blank=True, null=True)
    telegram = models.CharField(max_length=30, blank=True, null=True)
    skype = models.CharField(max_length=30, blank=True, null=True)
    discord = models.CharField(max_length=30, blank=True, null=True)
    alias = models.CharField(max_length=50, blank=True, null=True)
    usual_cost = models.IntegerField(blank=True, null=True,
                                     default=C_salary_common)
    high_cost = models.IntegerField(blank=True, null=True,
                                    default=C_salary_high)

    class Meta:
        verbose_name = _('Details')
        verbose_name_plural = _('Details')

    def __str__(self):
        return _('The UserDetail class: id = {}').format(self.user)

    def get_absolute_url(self):
        return reverse('student_detail_AP_url', kwargs={'pk': self.user.pk})


class TimeBlock(models.Model):
    """ Time blocking model in admin panel (AP) """

    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()

    class Meta:
        verbose_name = _('TimeBlock')
        verbose_name_plural = _('Timeblocks')
        ordering = ('date', 'start_time')

lessons_app/forms.py
import datetime

from django import forms
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext as _

from .models import Lesson, TimeBlock
from CalendarApi.constraints import (
    С_morning_time, C_evening_time,  C_timedelta,  C_datedelta
)


class RegisterUserForm(forms.Form):
    """Form for registration
    Use in views - CustomRegistration, template - registration.html"""

    username = forms.CharField(
        label=_('Username'),
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Enter your login'),
            'style': 'margin-bottom: 10px'
        })
    )
    password = forms.CharField(
        label=_('Password'),
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Enter your password'),
            'style': 'margin-bottom: 10px'
        })
    )
    first_name = forms.CharField(
        label=_('Name'),
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Enter your name'),
            'style': 'margin-bottom: 10px'
        })
    )
    phone = forms.CharField(
        label=_('Phone'),
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '89001234567',
            'style': 'margin-bottom: 10px'
        }),
        required=False
    )
    telegram = forms.CharField(
        label='Telegram',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '@nickname'
        }),
        required=False
    )

    def is_valid(self, request, form) -> bool:

        # username doen't contain spaces
        if len(form['username'].value().split()) > 1:
            messages.error(request, _("Username doen't contain spaces"))
            return False

        # password doen't contain spaces
        if len(form['password'].value().split()) > 1:
            messages.error(request, _("Password doen't contain spaces"))
            return False

        # phone or telegram must exist
        if form['phone'].value() == form['telegram'].value() == '':
            messages.error(
                request,
                _('You must provide a phone number or telegram nickname')
            )
            return False

        # check phone format
        if form['phone'].value() != '':
            try:
                int(form['phone'].value())
            except BaseException:
                messages.error(request, _("Phone number must be digits only"))
                return False
            if len(form['phone'].value()) != 11:
                messages.error(
                    request,
                    message=_("Phone number must contain 11 digits")
                )
                return False

        # check telegram format
        if form['telegram'].value() != '':
            if form['telegram'].value()[0] != '@':
                messages.error(
                    request,
                    message=_("Telegram nickname must start with '@..'")
                )
                return False
            if len(form['telegram'].value().split()) > 1:
                messages.error(
                    request,
                    message=_("Telegram nickname doen't contain spaces")
                )
                return False

        # check of login existence
        all_usernames = User.objects.values_list('username')
        all_usernames = {username[0] for username in all_usernames}
        if form['username'].value() in all_usernames:
            messages.error(
                request,
                message=_("This login exists")
            )
            return False

        return super().is_valid()


class AuthUserForm(AuthenticationForm, forms.ModelForm):
    """Form for authentication.
    Use in views - CustomLoginView, template - login.html"""
    # AuthenticationForm needed for using authentication

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs[
            'placeholder'] = _('Enter your username')
        self.fields['password'].widget.attrs[
            'placeholder'] = _('Enter your password')

    class Meta:
        model = User
        fields = ('username', 'password')

        # labels = {...}  doesn't work!
        # widgets = {...}  doesn't work!


class AddLessonForm(forms.Form):
    """ Create a new lesson by student """

    time = forms.IntegerField(
        label=_('Time'),
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
            'value': 15
        })
    )
    date = forms.CharField(
        label=_('Date'),
        widget=forms.Select(
            choices=[],
            attrs={
                'class': 'form-control'
            }
        )
    )

    def is_valid(self, request, form):
        try:
            time = str(form['time'].value()).split(':')[0]
            time = datetime.datetime.strptime(time, r"%H").time()
        except ValueError:
            messages.error(
                request,
                _("Time must be in 'hours' or "
                    "'hours:minutes' format")
            )
            return False

        date = datetime.datetime.strptime(
            form['date'].value(),
            r"%Y-%m-%d"
        ).date()

        dt_now = datetime.datetime.now()

        # sign up is impossible for past date or today + 8 days
        if datetime.datetime.combine(date, time) < dt_now:
            messages.error(
                request,
                _("The date {} has already arrived").format(date)
            )
            return False
        elif date > (dt_now + C_datedelta).date():
            messages.error(
                request,
                _("Please don't book a lesson earlier then {} "
                  "days in advace").format(C_datedelta.days)
            )
            return False

        # sign up is impossible for next 3 hours
        if datetime.datetime.combine(date, time) < dt_now + C_timedelta:
            messages.error(
                request,
                _("Please, sign up for a lesson {} hours before to "
                  "start").format(C_timedelta)
            )
            return False

        # constraint of working hours (8-23)
        if time < С_morning_time:
            messages.error(request, _("The time {} is too early").format(time))
            return False
        elif time > C_evening_time:
            messages.error(request, _("The time {} is too late").format(time))
            return False

        # free time check
        queryset = Lesson.objects.filter(date=date).values_list('time')
        times = [item[0] for item in queryset]
        for t1 in times:
            t2 = datetime.time(t1.hour+1, t1.minute, t1.second)
            if t1 <= time < t2:
                messages.error(
                    request,
                    _("Some lesson is already scheduled for {} that "
                      "day").format(t1)
                )
                return False

        # check blocked time overlap
        blocked_times = TimeBlock.objects.filter(date=date).values(
            'start_time', 'end_time')
        for blocked_time in blocked_times:
            if (blocked_time['start_time'] <= time < blocked_time['end_time']
                    or time == blocked_time['end_time'] == datetime.time(23)):
                messages.error(
                    request,
                    _("This time is blocked")
                )
                return False

        # super consist variable because it is used by AddLessonAdminForm class
        return super(forms.Form, self).is_valid()


class AddLessonAdminForm(forms.Form):
    """ Create a new lesson for students by admin """

    student = forms.CharField(
        label=_('Student'),
        widget=forms.Select(
            choices=[],  # is taken from view (get_context_date AddLessonAP)
            attrs={
                'class': 'form-control',
                'size': 10
            }
        )
    )
    time = forms.IntegerField(
        label=_('Time'),
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
            'placeholder': '00:00',
            'value': 15
        })
    )
    date = forms.CharField(
        label=_('Date'),
        widget=forms.Select(
            choices=[],  # is taken from view (get_context_date AddLessonAP)
            attrs={
                'class': 'form-control'
            }
        )
    )

    def is_valid(self, request, form):
        try:
            time = str(form['time'].value()).split(':')[0]
            time = datetime.datetime.strptime(time, r"%H").time()
        except ValueError:
            messages.error(
                request,
                _("Time must be in 'hours' or "
                    "'hours:minutes' format")
            )
            return False

        date = datetime.datetime.strptime(
            form['date'].value(),
            r"%Y-%m-%d"
        ).date()

        if form['student'].value() == '':
            messages.error(
                request,
                _("Please, select a student")
            )
            return False

        # check blocked time overlap
        blocked_times = TimeBlock.objects.filter(date=date).values(
            'start_time', 'end_time')
        for blocked_time in blocked_times:
            if (blocked_time['start_time'] <= time < blocked_time['end_time']
                    or time == blocked_time['end_time'] == datetime.time(23)):
                messages.error(
                    request,
                    _("This time is blocked")
                )
                return False

lessons_app/templates/lessons_app/add_lesson.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<h3>{% translate "To schedule" %}</h3>
<div class="row">
    <div class="col" style="max-width: 400px;">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p>
                <a href="#" class="thumbnail" data-bs-toggle="modal" data-bs-target="#M_sign_up" style="color: black; font-size: 9pt;">{% translate "How to take time?" %}</a><br>
                <a href="#" class="thumbnail" data-bs-toggle="modal" data-bs-target="#M_cost" style="color: black; font-size: 9pt;">{% translate "How to find out the cost?" %}</a>
            </p>
            <button type='submit' class='btn btn-primary btn-block'>{% translate "Add lesson" %}</button>
        </form>
    </div> 
</div>

<div class="modal fade" id="M_sign_up" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content" style="padding-bottom: 10px;">
            <div class="modal-header">
                <h5 class="modal-title" style="white-space: normal">
                    {% translate "How to take time?" %}
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <p style="white-space: normal; text-align: left; padding: 10px; margin-bottom: 0;">
                {% blocktranslate %}You must choose date and time for recording. You can to sign up for a lesson {{ C_timedelta }} hours before it starts. Before creating a new lesson, visit the homepage and make the time isn't taken by another person. After creating a lesson, a label with your time will appear on the homepage. To delete a lesson, you need to follow the link “My lessons”.{% endblocktranslate %}
            </p>
            <p style="margin-bottom: 0; padding: 0px 10px;">{% translate "There are three types of labels on the homepage:" %}</p>
            
            <div class="table" style="padding: 0 10px;">
                <table>
                    <tbody>
                        <tr style="border-style: none;">
                            <td>
                                <div class="card" style="background-color: rgb(253, 216, 171); margin-bottom: 0; width: 80px; height: 25px;"></div>
                            </td>
                            <td style="font-weight: normal; padding: 0 5px;">
                                -
                            </td>
                            <td style="font-weight: normal; padding: 5px 0;">
                                {% translate "indicates that the time is taken by another person" %};
                            </td>
                        </tr>
                        <tr style="border-style: none;">
                            <td>
                                <div class="card" style="background-color: rgb(167, 255, 226); margin-bottom: 0; width: 80px; height: 25px;"></div>
                            </td>
                            <th style="font-weight: normal; padding: 0 5px;">
                                -
                            </td>
                            <th style="font-weight: normal; padding: 5px 0;">
                                {% translate "indicates your own lesson" %};
                            </td>
                        </tr>
                        <tr style="border-style: none;">
                            <td>
                                <div class="card" style="background-color: rgb(255, 200, 200); margin-bottom: 0; width: 80px; height: 25px;"></div>
                            </td>
                            <th style="font-weight: normal; padding: 0 5px;">
                                -
                            </td>
                            <th style="font-weight: normal; padding: 5px 0;;">
                                {% translate "indicates that at this time I will not be able to teach" %};
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="M_cost" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" style="white-space: normal">
                    {% translate "How to find out the cost?" %}
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <p style="white-space: normal; text-align: left; padding: 10px;">
                {% for message in cost_messages %}
                    {{ message }} <br>
                {% endfor %}
            </p>
        </div>
    </div>
</div>
{% endblock content %}

lessons_app/templates/lessons_app/index.html
{% extends 'base.html' %}
{% load i18n %}
{% load extra_tags %}

{% block content %}
<div class="container testimonial-group">
    <div class="row text-center">
        <div class="row flex-nowrap">
            {% for day, lesson_by_day in lessons.items %}
                <div class="col" style="min-width: 140px; padding: 0;">
                    <h5 style="margin-bottom: 0rem">{{day|date:"l"}}</h5>
                    <p>{{day|date:"j E"}}</p>
                    
                    {% for lesson in lesson_by_day %}
                        {% is_TimeBlock lesson as is_block %}
                        {% if is_block %}
                            {% include 'lessons_app/inc/card_of_blocked_time.html' %}
                        {% else %}
                            {% include 'lessons_app/inc/card_of_lesson.html'%}
                        {% endif %}

                        {% if request.user.is_staff %}
                            {% include "lessons_app/inc/_lesson_modal.html" %}
                        {% endif %}
                    {% endfor %}
                    
                </div>
            {% endfor %}
        </div>
    </div>
</div>
<div class="d-none d-sm-none d-md-block">
    <p style="color: #9a9ea3;">{% translate "Horizontal scrolling is possible with the wheel and the Shift key pressed" %}</p>
</div>
{% endblock content %}

lessons_app/templates/lessons_app/info.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<h3 style="margin-bottom: 15px;">{% translate 'About me' %}</h3>
<div class="row">
    <div class="d-none d-sm-none d-md-none d-lg-none d-xl-block">
        <img src="{% static 'img/photo.jpg' %}" alt="photo" style="margin-right: 40px; margin-bottom: 20px; float: left;">
        {% include 'lessons_app/inc/info/_bio.html' %}
        <div class="d-none d-sm-none d-md-none d-lg-none d-xl-none d-xxl-block">
            {% include 'lessons_app/inc/info/_contacts.html' %}
        </div>
    </div>
    <div class="d-none d-sm-none d-md-none d-lg-none d-xl-block d-xxl-none">
        {% include 'lessons_app/inc/info/_contacts.html' %}
    </div>
    <div class="d-block d-sm-block d-md-block d-lg-block d-xl-none">
        <div style="text-align: center;">
            <img src="{% static 'img/photo.jpg' %}" alt="photo" style="max-width: 500px; width: 100%; margin-bottom: 20px;">
        </div>
        {% include 'lessons_app/inc/info/_bio.html' %}
        {% include 'lessons_app/inc/info/_contacts.html' %}
    </div>
    {% include 'lessons_app/inc/info/_how_site_works.html' %}
</div>
{% endblock content %}

lessons_app/templates/lessons_app/lessons_by_student.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<h3>{% translate "My lessons" %}</h3>
<div class="container">
    <div class="row">
        <div class="col-2" style="min-width: 200px; padding-top: 20px;">
            <p>{% translate "Name" %}: {{ request.user.first_name }}</p>
            {% if request.user.details.phone %}
            <p>{% translate "Phone" %}: {{ request.user.details.phone }}</p>
            {% endif %}
            {% if request.user.details.telegram %}
            <p>{% translate "Telegram" %}: {{ request.user.details.telegram }}</p>
            {% endif %}
            <p><a href="#" class="btn btn-primary btn-block" data-bs-toggle="modal" data-bs-target="#M_change_password" style="width: 160px;">{% translate "Change password" %}</a></p>
        </div>
        <div class="col">
            <div class="container testimonial-group">
                <div class="row justify-content-center">
                    <div class="table" style="max-width: 900px;">
                        <table class="table table-striped">
                            <thead class="thead-light">
                                <tr>
                                    <th style="width: 5%; text-align: center; min-width: 60px;" ><h5>Id</h5></th>
                                    <th style="width: 15%; text-align: center; min-width: 130px;" ><h5>{% translate "Date" %}</h5></th>
                                    <th style="width: 15%; text-align: center; min-width: 100px;" ><h5>{% translate "Time" %}</h5></th>
                                    <th style="width: 10%; text-align: center; min-width: 70px;" ><h5>{% translate "Cost" %}</h5></th>
                                    <th style="width: 10%; min-width: 100px;" ></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for lesson in lessons %}
                                <tr>
                                    <th style="vertical-align: middle; text-align: center;">
                                        {{ lesson.id }}
                                    </th>
                                    <th style="vertical-align: middle; text-align: center;">
                                        {{ lesson.date|date:"j b, D" }}
                                    </th>
                                    <th style="vertical-align: middle; text-align: center;">
                                        {{ lesson.time|date:"G:i" }}
                                    </th>
                                    <th style="vertical-align: middle; text-align: center;">
                                        {{ lesson.salary }} ₽
                                    </th>
                                    <th style="vertical-align: middle; text-align: center;">
                                        <form id="delete_{{ lesson.pk }}" action="{% url 'del_lesson_url' lesson.pk %}" method="post">
                                            {% csrf_token %}
                                            <button type='submit' class='btn btn-danger btn-block' style="padding: 6px 12px 6px 6px; width: 100%; width: 50px; padding: 6px 0px;">
                                                <img src="{% static 'img/white-cross.png' %}" alt="delete" width="20px">
                                            </button>
                                        </form>
                                    </th>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="M_change_password" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 style="margin-bottom: 0;">{% translate "Password change" %}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post">
                    {% csrf_token %}
                    <p style="margin-bottom: 0;">{% translate "Enter a new password" %}</p>
                    <input class="form-control" type="text" name="new_password" required>
                    <div class="row justify-content-center">
                    <p style="margin-top: 15px; width: 184px;">
                        <button type='submit' class='btn btn-primary btn-block' style="width: 160px;">{% translate "Change password" %}</button>
                    </p>
                    </div>
                </form>
            </div>
            
        </div>
    </div>
</div>

{% endblock content %}

lessons_app/templates/lessons_app/login.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

<h3>{% translate "Authenticate" %}</h3>
<div class="row">
    <div class="col" style="max-width: 400px;">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type='submit' class='btn btn-primary btn-block'>{% translate "Log in" %}</button>
        </form>
    </div>
</div>

{% endblock content %}

lessons_app/templates/lessons_app/registration.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}

<h3>{% translate "Registration" %}</h3>
<div class="row">
    <div class="col" style="max-width: 400px;">
        <form method="post">
            {% csrf_token %}
            <p>
                <label for="id_username" class="form-label">{{ form.username.label }}</label>
                {{ form.username }}
                <div class="invalid-feedback">
                    {{ form.username.errors }}
                </div>
            </p>
            <p>
                <label for="id_password" class="form-label">{{ form.password.label }}</label>
                {{ form.password }}
                <div class="invalid-feedback">
                    {{ form.password.errors }}
                </div>
            </p>
            <p>
                <label for="id_first_name" class="form-label">{{ form.first_name.label }}</label>
                {{ form.first_name }}
                <div class="invalid-feedback">
                    {{ form.first_name.errors }}
                </div>
            </p>
            <p>
                <label for="id_phone" class="form-label">{{ form.phone.label }}</label>
                {{ form.phone }}
                <div style="margin-bottom: 0; margin-left: 13px; margin-top: -18px;color: #8f9397; font-size: 10pt;">{% translate "options" %}</div>
                <div class="invalid-feedback">
                    {{ form.phone.errors }}
                </div>
            </p>
            <p>
                <label for="id_telegram" class="form-label">{{ form.telegram.label }}</label>
                {{ form.telegram }}
                <div style="margin-bottom: 0; margin-left: 13px; margin-top: -18px;color: #8f9397; font-size: 10pt;">{% translate "options" %}</div>
                <div class="invalid-feedback">
                    {{ form.telegram.errors }}
                </div>
                <p style="color: black; font-size: 9pt; margin: 3px 0px;">
                    {% translate "How to find out a telegram nickname on a " %}
                    <a href="#" class="thumbnail" data-bs-toggle="modal" data-bs-target="#telegram_computer">{% translate "computer" %}</a>
                    {% translate " and " %}
                    <a href="#" class="thumbnail" data-bs-toggle="modal" data-bs-target="#telegram_phone">{% translate "phone" %}</a>?
                </p>
            </p>
            <button type='submit' class='btn btn-primary btn-block'>{% translate "Send" %}</button>
        </form>
    </div>
</div>

{% include 'lessons_app/inc/telegram_modal_for_computer.html' %}
{% include 'lessons_app/inc/telegram_modal_for_phone.html' %}

{% endblock content %}